AllCops:
  Exclude:
    - db/schema.rb

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*_test.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/**/*_context.rb'
  ExcludedMethods:
    - resource
    - params
    - requires
    - route_param

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/factories/**/*.rb'
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
    - uniq
    - git_source
    - its
    - sequence
    - default_scope

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/SingleLineMethods:
  Exclude:
    - 'app/policies/application_policy.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'app/policies/*_policy.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
